name: smarttrash
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2
  cupertino_icons: ^0.1.2
  charts_flutter: ^0.8.0
  firebase_database: ^0.4.1
  firebase_core: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/LOGO12.png"
  image_path_android: "assets/LOGO12.png"

flutter:

  uses-material-design: true

  assets:
        - assets/login_logo.png
        - assets/LOGO12.png
        - assets/charts1.png
  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

